liberapay: sadko4u
patreon: sadko4u
custom:
- https://www.blockchain.com/btc/address/15X3AfDRF3EshSLBoK8UfHAsFr2TQsH8pk
- https://etherscan.io/address/0x079b24da78d78302cd3cfbb80c728cd554606cc6
- https://www.bountysource.com/teams/lsp-plugins
- https://paypal.me/sadko4u
